name: Cypress Tests

on: 
  repository_dispatch:
    types: test

jobs:
  set_shared_env_vars:
    name: Test Run Setup
    runs-on: ubuntu-latest
    env:
        cypress_suprise: From a different job!!!
        cypress_baseUrl: ${{ secrets.cypress_baseUrl }}
        cypress_admin_login: ${{ secrets.cypress_admin_login }}
        cypress_admin_pwd: ${{ secrets.cypress_admin_pwd }}
        cypress_TEST_PROJECT_ID: ${{ secrets.cypress_TEST_PROJECT_ID }}
        slack_webhooks_url: ${{ secrets.slack_webhooks_url }}


    steps:
      - name: Step 1 => Checkout
        uses: actions/checkout@v1
        
      - name: Step 2 => printenv
        run: |
          printenv

      - name: Step 3 => build
        run: |
          npm install
          npm run test
