name: Cypress Tests

on: 
  repository_dispatch:
    types: test

jobs:
  set_shared_env_vars:
    name: Test Run Setup
    runs-on: ubuntu-latest
    env:
        cypress_suprise: From a different job!!!
        cypress_baseUrl: ${{ secrets.cypress_baseUrl }}
        cypress_admin_login: ${{ secrets.cypress_admin_login }}
        cypress_admin_pwd: ${{ secrets.cypress_admin_pwd }}
        cypress_TEST_PROJECT_ID: ${{ secrets.cypress_TEST_PROJECT_ID }}
        slack_webhooks_url: ${{ secrets.slack_webhooks_url }}
        slack_recipient: "@${{ github.event.client_payload.user_name }}"
        slack_response_url: ${{ github.event.client_payload.response_url }}

    steps:
      - name: Step 1 => Checkout
        uses: actions/checkout@v1

      - name: Step 2 => Acknowledge Receipt
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hey there! Your build is about to fire up!!", "channel": "$slack_recipient"}' $slack_webhooks_url
          printenv
          echo "Client Payload.user_name: ${{ github.event.client_payload.user_name }}"
          echo "Client Payload.response_url: ${{ github.event.client_payload.response_url }}"

      - name: Step 3 => Install Python Reqs
        run: |
          python -V
          pip -V
          pip install --trusted-host pypi.python.org -r requirements.txt
          curl -X POST -H 'Content-type: application/json' --data '{"text":":successful: Python libs installed!", "channel": "$slack_recipient"}' $slack_webhooks_url

      - name: Step 4 => build
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Starting npm install", "channel": "$slack_recipient"}' $slack_webhooks_url
          npm install
          curl -X POST -H 'Content-type: application/json' --data '{"text":":successful: Cypress is starting now!", "channel": "$slack_recipient"}' $slack_webhooks_url
          npm run test

      - name: Step 5 => Notify via Slack
        run: |
          npm run notify
