name: Cypress Tests

on: 
  repository_dispatch:
    types: test

jobs:
  set_shared_env_vars:
    name: Test Run Setup
    runs-on: ubuntu-latest
    env:
        cypress_suprise: From a different job!!!
        cypress_baseUrl: ${{ secrets.cypress_baseUrl }}
        cypress_admin_login: ${{ secrets.cypress_admin_login }}
        cypress_admin_pwd: ${{ secrets.cypress_admin_pwd }}
        cypress_TEST_PROJECT_ID: ${{ secrets.cypress_TEST_PROJECT_ID }}
        slack_webhooks_url: ${{ secrets.slack_webhooks_url }}
        slack_recipient: "@${{ github.event.client_payload.user_name }}"
        slack_response_url: ${{ github.event.client_payload.response_url }}

    steps:
      - name: Step 1 => Checkout
        uses: actions/checkout@v1

      - name: Step 2 => Print client_payload vars 
        run: |
          echo "Client Payload.user_name: ${{ github.event.client_payload.user_name }}"
          echo "Client Payload.response_url: ${{ github.event.client_payload.response_url }}"
        
      - name: Step 3 => printenv
        run: |
          printenv

      - name: Step 4 => build
        run: |
          npm install
          npm run test

      - name: Step 5 => Notify via Slack
        run: |
          npm run notify
